url: symbolb.com
baseurl:

# Site settings
title: Symbol B
email: support@symbolb.com
description: ""

# Team names, titles and social links
people:
- name: First Last
  pic: 1
  position: Senior Manager

- name: First Last
  pic: 2
  position: Technical Development Lead

- name: First Last
  pic: 3
  position: Sales & Training Lead


# Postal address (add as many lines as necessary)
address:
  - line: Calgary
  - line: Alberta, CA

# Build settings
markdown: kramdown
permalink: pretty
